#CPU usage three shold
CPU_LIMIT=80

# RAM Usage threshold
RAM_LIMIT=80

#disk usage threshold
DISK_LIMIT=80

#Service to Monitor
SERVICE_NAME=nginx

#log files
LOG_FILE=logs/monitor.log

#RCA directory
RCA_DIR=rca
